disabled_rules:
  - line_length
  - type_body_length
  - function_body_length
  - file_length
  - cyclomatic_complexity
  - trailing_whitespace
  - todo
  - opening_brace

opt_in_rules:
  - toggle_bool

analyzer_rules:
 - unused_import
 - unused_declaration

excluded:
  - .build
